### PR TITLE
LSM303AGR

### PR DESCRIPTION
**Pull request by alankrantas**
Works pretty well for me.  And since this is primary created for micro:bit v1.5, I included the math package to added some functions to provide data like pitch, roll, compass heading (the "compass" is not so accurate though, even in MakeCode) as well as the built-in temperature sensor.

### CODE REVIEW

**Comment by conejoninja** [comment]
I remember @aykevl had some functions for pitch/roll somewhere too, I'm unable to find it now. I think we could/should create accelerometer/magnometer/compasser interfaces and a package with those common functions. What do you think?

**Comment by alankrantas** [comment]
@conejoninja probably be a good idea when there are more similar sensors added.

There are also formulas to calculate gyroscope motions, but I never understand them.

(And anyone knows what's the deal with the failing CI format check?)

**Comment by deadprogram** [comment]
Hi @alankrantas you can run `go fmt ./examples/lsm303agr/main.go` which should resolve that, then please commit and push the updated version. Thanks!

**Comment by alankrantas** [comment]
Tried to format it and upload the file directly. Still not working.

(It's dragon boat festival today, and I probably need to throw a few rice cakes to feed this CI monster.)

**Comment by deadprogram** [comment]
Your last commit got past that, how it is a different error. Please rebase your branch against the current `dev` branch and push again.

**Comment by alankrantas** [comment]
Ok...I have no idea how to do rebase online. Should I make a new PR? Or make a new branch at my fork?

**Comment by deadprogram** [comment]
The easiest thing would be create a new branch based on `dev`, then add your new changes on top of that.

Also, while you are at it, please add a smoke test like this: https://github.com/tinygo-org/drivers/blob/dev/Makefile#L142-L143

Thank you.

**Comment by aykevl** [comment]
Yes, I have a package here: https://github.com/aykevl/fusion
The main issue with it is that it doesn't expose yaw/pitch/roll but that could be added. So far I've mainly (tried to) use it for things that do not have an obvious up/down side so the yaw/pitch/roll format didn't make a lot of sense. Improvements are welcome.

**Pull request closed without merging**
