### PR TITLE
README: add README with project scope and contributing guidelines

### PR DESCRIPTION
**Pull request by aykevl**
@deadprogram what do you think, especially of the project scope? I think it's useful to decide such things from the beginning so everyone knows what is and is not in scope.

Also, I just realize there is no license yet, that should be the same one as the TinyGo license (3-clause BSD).

### CODE REVIEW

**Comment by deadprogram** [comment]
I think there is simple way to state "These drivers provide low-level access to the device functionality." 

I do not agree with the statement that "many of these drivers are not meant to
be used directly". They are in fact meant to do exactly that IMO, and nothing else.

**Comment by deadprogram** [comment]
I used the basic idea but created an entirely different README. Closing this PR, please open another with any edits.

**Comment by aykevl** [comment]
Which PR? This is for the drivers repo, which doesn't have a README yet.

**Comment by deadprogram** [comment]
I added a README already, is what I am saying in https://github.com/tinygo-org/drivers/pull/10#issuecomment-461326090

**Comment by aykevl** [comment]
Oops, didn't look good enough... Sorry about that.

**Pull request closed without merging**
