### PR TITLE
wifinina: add mutex to prevent communication race problems

### PR DESCRIPTION
**Pull request by deadprogram**
This PR adds a mutex to the WifiNINA driver to prevent communication race problems when multiple goroutines try to access adaptor at the same time.

### CODE REVIEW

**Comment by ysoldak** [comment]
Why don’t put mutex on all public methods? Basically any “concurrent” access to wifinina upsets communication. Like one goroutune does networking, another does RGB leds…

**Comment by deadprogram** [comment]
@ysoldak I tried to only use the mutex where it seemed absolutely needed. Are there any specific functions you think I should cover that I missed, or is this more of a general comment?

**Comment by ysoldak** [comment]
@deadprogram general comment, yes.

**Comment by deadprogram** [comment]
That being the case, I will merge this and then further improvements can continue from there. Thanks @ysoldak

**Pull request merged**
