### PR TITLE
Add Waveshare 4.2in B/W e-paper driver

### PR DESCRIPTION
**Pull request by timboldt**
Like the other EPD drivers in this repo, this driver is a direct port of the Waveshare reference implementation for Arduino, located at https://github.com/waveshare/e-Paper.

### CODE REVIEW

**Comment by conejoninja** [comment]
It looks fine and I assume this is working properly too.
Thanks for your contribution, great addition.

**Comment by conejoninja** [comment]
One thing missing before merging this PR, is to add the driver to the README.md list and to the smoke-tests (Makefile)

**Comment by timboldt** [comment]
It looks like I should do something like this? i.e. Add it to the README list, add an example, and add the example to the makefile.

https://github.com/tinygo-org/drivers/commit/fd9b1ba89b58be6d70df1973ad4b1746fbd3f360

**Comment by conejoninja** [comment]
yes exactly that, have in mind that the number of devices (in README.md file) should be 53. Your base branch has "51", but a new driver was accepted, bumping the number to 52, this driver will be the 53th

**Comment by deadprogram** [comment]
hI @timboldt can you please also add a smoke test for the new driver like this: https://github.com/tinygo-org/drivers/blob/dev/Makefile#L156-L157

Thank you.

**Comment by timboldt** [comment]
Will do.

**Comment by deadprogram** [comment]
Thank you very much for working on this! @timboldt now squash/merging.

**Comment by sago35** [comment]
link : #181

**Pull request merged**
