### PR TITLE
net: fix tcp connection raddr

### PR DESCRIPTION
**Pull request by ysoldak**
One more typo fix

### CODE REVIEW

**Comment by ysoldak** [comment]
I thought we have a fix in tinygo repo for these CircleCi builds? Still failing though, @aykevl @deadprogram

**Comment by deadprogram** [comment]
"The fix is in" as they say. Rebuilding all now passes.

**Comment by ysoldak** [comment]
Cool, this trivial PR is green again!

**Comment by deadprogram** [comment]
Trivial, but needed. Thanks, now merging.

**Pull request merged**
