### PR TITLE
wifinina: add support for http server

### PR DESCRIPTION
**Pull request by scottfeldman**
This adds http.ListenAndServe() implementation for wifinina.  Included is an example webserver, basically copied from the rtl8720dn/webserver.

Tested on Arduino Nano RP2040 Connect.  Also tried testing on Arduino Nano33 IoT but test panics with "out of memory".  There's only 32K of SRAM on the Nano33, vs 264K on the rp2040 Connect.

### CODE REVIEW

**Comment by sago35** [comment]
I will check this weekend.

**Review by sago35 — APPROVED** [review]
LGTM

Source code verified.
I think it is very good.

I also tried running it on PyPortal.
I was able to confirm that it is working correctly.

**Comment by deadprogram** [comment]
Thank you for the addition @scottfeldman and to @sago35 for review. Now going to squash/merge.

**Comment by fangyygw** [comment]
out of memory in  Arduino-Nano33-iot

**Comment by scottfeldman** [comment]
@fangyygw Yes, arduino-nano33 doesn't have enough SRAM (32KB) to support http server.  Alternate boards that can use wifinina for http server are: nano-rp2040, pyportal, metro-m4-airlift, and matrixportal-m4.

**Pull request merged**
