### PR TITLE
examples: add example for mag3110 magnetometer

### PR DESCRIPTION
**Pull request by deadprogram**
This PR adds an example for mag3110 magnetometer. Not very much to it.

### CODE REVIEW

**Comment by aykevl** [comment]
While useful, I think it will be much more useful when you get some usable data out of it. By default, the magnetometer needs to be calibrated (this is an inherent limitation of all magnetometers).

Also, but that's a comment on the driver itself (which I wrote), the units should be much better defined. Currently they simply return the raw values while they should return values in a standard ISO unit. That would make calibration much easier too as you know the range.

**Comment by deadprogram** [comment]
You can add to the example when you update the driver. Right now there is no example at all, which is what this PR tries to address. I intend to submit a basic example for each driver that currently lacks one in various PRs.

**Comment by deadprogram** [comment]
Any further comments, or can this get merged? We can extend the sample once the driver functionality is extended.

**Comment by aykevl** [comment]
Fair enough.

**Pull request merged**
