### PR TITLE
lorawan: Update AU915 RegionSet configuration

### PR DESCRIPTION
**Pull request by ofauchon**
This PR provides valid settings for AU915 Lorawan Region.

Thanks to @tcpipchip for helping us in tuning and validating this new configuration
(Tested on local AU Chirpstack gateway and AU TTN network)

### CODE REVIEW

**Comment by deadprogram** [comment]
Thank you very much @ofauchon for the fixes and to @tcpipchip for testing! Now merging.

**Comment by tcpipchip** [comment]
845 uplinks done without error using AU915, until now

**Comment by tcpipchip** [comment]
> Thank you very much @ofauchon for the fixes and to @tcpipchip for testing! Now merging.

:)

**Comment by tcpipchip** [comment]
> This PR provides valid settings for AU915 Lorawan Region.
> 
> Thanks to @tcpipchip for helping us in tuning and validating this new configuration (Tested on local AU Chirpstack gateway and AU TTN network)

:)

**Comment by tcpipchip** [comment]
Hi, still testing! Something like ABP ?
Btw, plans to use lora mesh ?

**Pull request merged**
