### PR TITLE
makeybutton: add driver for MakeyMakey-like button

### PR DESCRIPTION
**Pull request by deadprogram**
This PR adds a driver for a MakeyMakey-like button (https://makeymakey.com/)

### CODE REVIEW

**Comment by sago35** [comment]
How is makeybutton connected to the microcontroller?

**Comment by conejoninja** [comment]
> How is makeybutton connected to the microcontroller?

it isn't?

Makeymakey has its own micro (atmega32u4), by the example provided I guess this is kind of an interface similar to makeymakey. Otherwise it will need an special firmware to be connected as a device ??

**Comment by deadprogram** [comment]
This is not to connect a MakeyMakey. It is to use a pin of whatever MCU to act like a MakeyMakey does by connecting a high Ohm resistor.

**Comment by deadprogram** [comment]
Circuit:
image

**Comment by conejoninja** [comment]
It's ok for me, merging

**Pull request merged**
