### PR TITLE
buzzer: add pwm version buzzer

### PR DESCRIPTION
**Pull request by sago35**
In this PR, the PWM version buzzer will be added.

The difference in sound when using Wio Terminal is as follows.
https://twitter.com/sago35tk/status/1488848571533500416?s=20&t=aN3Y_Qsd0aHKMxuwVQn-Vg

### CODE REVIEW

**Comment by sago35** [comment]
Make it depend on PWM interface instead of machine.TCC.
The machine.TCC is probably only present in samd.

**Comment by deadprogram** [comment]
Small change, perhaps better to name the example here `buzzer-pwm` instead of `buzzer2`? Seems more meaningful.

**Comment by sago35** [comment]
@deadprogram 
You are right.
If the review is OK, squash merge when you merge.
Please let me know if you have any other remarks.

**Comment by aykevl** [comment]
We already have something very similar to this, the tone driver. How is this different?

**Comment by sago35** [comment]
Oops, I didn't know there was such a thing as a tone driver.

**Comment by sago35** [comment]
I modified the source code so that CI would succeed.
However, this PR is unnecessary and can be closed.

**Pull request closed without merging**
