### PR TITLE
Mpu9150

### PR DESCRIPTION
**Pull request by francdoc**

### CODE REVIEW

**Comment by francdoc** [comment]
@deadprogram Hi, can you review this please?

**Comment by deadprogram** [comment]
Hello @FranCDoc thanks for the new device code.

Can you please add a smoke test for it here: https://github.com/tinygo-org/drivers/blob/dev/smoketest.sh

Thanks!

**Comment by deadprogram** [comment]
Also please add an example of use for the smoketest. Thanks!

**Comment by francdoc** [comment]
Hi @deadprogram. Thanks for your answer. I updated it as requested.

**Comment by deadprogram** [comment]
Thank you for the addition @FranCDoc now squashing/merging.

**Comment by fchiesad** [comment]
Thanks @deadprogram.

**Comment by francdoc** [comment]
Thanks @deadprogram.

**Pull request merged**
