### PR TITLE
microbitmatrix: fix for dev branch / volatile package/API

### PR DESCRIPTION
**Pull request by conejoninja**
This commit ( https://github.com/tinygo-org/tinygo/commit/9f8340a97065c4868dae0d434967183c7a8b1bc6 ) broke the current microbit matrix driver and the CI for the rest

### CODE REVIEW

**Comment by deadprogram** [comment]
The volatile package API now requires that you use `Set()`/`Get()` functions.

However, I think this is what the `PortMaskSet()` and `PortMaskClear()` functions are intended for, instead of directly changing register values. 

It would appear that you will also need a `PortMaskDir()` to handle the needs of this driver:
https://github.com/tinygo-org/tinygo/blob/dev/src/machine/machine_nrf.go#L37-L49

What do you think?

**Comment by conejoninja** [comment]
I'll take a deeper look at the changes, I didn't fully understand them, just saw the regValue => Set change and follow with it :laughing: I see now  I could have used PortMaskSet/Clear. Thanks!

**Comment by conejoninja** [comment]
I'm a bit confused on how to use the PortMaskSet/Clear as they only return the register (nrf.GPIO.OUTSET / nrf.GPIO.OUTCLR ¿?) and the mask. For changing the value I still need to use Set (or SetBits but that will change the register multiple times instead of one) on the register and with the mas returned from portMaskSet/Clear, did I understand it correctly? And to use PortMaskSet/Clear I need to previously configure the 12 pins individually (so I have a GPIO struct from the pin number). I see a lot of extra steps, I'm probably missing something, why not use the GPIO.High()/Low() directly?

**Comment by deadprogram** [comment]
The functions return a `*uint32` so you can just change it directly, ala

```go
portClear, _ := d.Pin.PortMaskClear()
set := 0
for col := 0; col < 9; col++ {
	if d.buffer[row][col] {
		set |= 1 << uint8(machine.LED_COL_1+col)
	}
}
*portClear |= set // changes all the bits at same time
```

That said, if you can just change each pin individually, better to use the GPIO interface, as you mention.

**Comment by deadprogram** [comment]
Thanks for the fix @conejoninja now merging.

**Comment by aykevl** [comment]
Late comment from me: yes using just `High()` and `Low()` is better as it avoids a dependency on the device/nrf package.

The example in https://github.com/tinygo-org/drivers/pull/63#issuecomment-495914625 is actually subtly wrong as it does not use volatile and thus may not do what you expect. `PortMaskSet` and `PortMaskClear` are really intended for low-level bitbanging (in assembly), like in the ws2812 driver. See that driver for an example.

**Pull request merged**
