### PR TITLE
Netdev changes - rebased

### PR DESCRIPTION
**Pull request by deadprogram**
This PR is basically https://github.com/tinygo-org/drivers/pull/537 but fully rebased against the latest `dev`

### CODE REVIEW

**Comment by deadprogram** [comment]
Passes all smoke tests when run against https://github.com/tinygo-org/tinygo/tree/net-submodule-netdev3

**Comment by deadprogram** [comment]
When attempting to compile the "examples/socket" program, I get the following error:

```
# tinygo.org/x/drivers/examples/net/socket
examples/net/socket/main.go:64:33: too many arguments in call to dev.Connect
        have (int, string, net.IP, int)
        want (int, string, netip.AddrPort)
examples/net/socket/main.go:65:50: too many arguments in call to dev.Connect
        have (int, string, net.IP, int)
        want (int, string, netip.AddrPort)
```

cc @scottfeldman

**Comment by scottfeldman** [comment]
> When attempting to compile the "examples/socket" program, I get the following error:
> 
> ```
> # tinygo.org/x/drivers/examples/net/socket
> examples/net/socket/main.go:64:33: too many arguments in call to dev.Connect
>         have (int, string, net.IP, int)
>         want (int, string, netip.AddrPort)
> examples/net/socket/main.go:65:50: too many arguments in call to dev.Connect
>         have (int, string, net.IP, int)
>         want (int, string, netip.AddrPort)
> ```

Fixed in https://github.com/tinygo-org/drivers/pull/623.  Missed some updates to examples when converting to net/netip APIs.

**Comment by deadprogram** [comment]
Now that PR https://github.com/tinygo-org/tinygo/pull/3704 has been merged, the tests in this branch are passing!

**Comment by deadprogram** [comment]
I've rebased it down to 14 commits. Now merging. Thank you very much @scottfeldman @soypat and everyone else who helped work on this.

**Pull request merged**
