### PR TITLE
Fix Wifnina for Firmware >= 1.2.4

### PR DESCRIPTION
**Pull request by Nerzal**
I know the fix is kinda dirty, but i couldn't wrap my head around how to get it into the existing padding logic. 
If anyone has an idea, tell me :) 

I tested the mqttclient, tcpclient and udpstation and they all worked. 
Only thing i wasn't able to fix is the tls issue, guess I'll need more time for that. 

Tested with Firmware 1.2.4 and 1.4.3 :) 

Fixes: #233

### CODE REVIEW

**Comment by Nerzal** [comment]
Just found the this branch from @bgould where a tremendous amount of work has already been done to bring that wifina implementation into a clean form. I guess that would be a great starting point for future refactorings.

https://github.com/bgould/drivers/tree/wifinina-refactor

**Comment by Nerzal** [comment]
I'm going to try to finish the great work on that branch starting tomorow, so ignore that PR for some days, as i'm going to update it :)

**Comment by Nerzal** [comment]
closing in favor of a new branch, that is based on the refactored wifina driver

**Comment by deadprogram** [comment]
Did you ever get a chance to test the @bgould branch to see if it corrected the same issues you were having @Nerzal?

I am willing to work on this to help if it actually corrects the core issue.

Thanks!

**Comment by Nerzal** [comment]
I have a fork of that Branch, yes. Works pretty well, but im cant get the ntp example to run, also i have not yet found the reason why tls is not working.

**Comment by ysoldak** [comment]
I confirm @bgould 's branch works on my nano 33 iot board with v1.4.3 fw flashed via Arduino.app
So far I've been able to connect to my AP, gonna do more testing around.
My end goal is to be able to connect to AWS IoT with all that x509 keys, etc.

Spent some time yesterday trying figure out why wifinina would not work for me.
Was blaming myself before realising the code in this repo is outdated and would not work with latest versions of nina-fw.
Did some dirty hack similar to @Nerzal in my local copy to make it work, but happy to find there is better version out there.

I am curious, how do you guys want to proceed with wifinina? One way would be to keep parity with Arduino lib, re-implementing it close to original, but in Go. Yet it seem  @bgould took a different approach and has totally different implementation.

**Comment by ysoldak** [comment]
Can not make bgould's version to pass ntp test. Something is very wrong in there.
Look like random panics induced by that 48 byte buffer allocation (do not ask).
I'm switching to @Nerzal version. At least it works for me and works fine with ntp.

Would vote for re-oppening this PR and merging it already until we have anything better.
Right now wifinina driver is just plain broken.

**Comment by Nerzal** [comment]
We could merge this branch as a dirty fix, until the rewrite on some other branch is finished. 
If that is wished, i can open a new branch, implementing the dirty fix everywhere where needed.

I have some work done here, but still need more time to finish, as there are still problems :) 
https://github.com/Nerzal/drivers/tree/wifinina-refactor/wifinina

**Pull request closed without merging**
