### PR TITLE
Preliminary support for 9-axis accelerometer sensor MPU9250

### PR DESCRIPTION
**Pull request by conejoninja**
This adds basic support for MPU9250, the sensor has some more complex features that I plan to add at a later time, but I'd like to resolve some doubts before continuing the work (not sure if this is the correct place for such questions).

* Acceleration is returned in mG (Gravity/1000), should it be m/s² ?
* Rotation is returned in millidegrees/second, should it be rads/second?
* Magnetometer values should be returned in µT, but I'm getting very low values, oddly enough, the horizontal directions seems to be the correct one (in milliDegrees, should be in rads too?)

### CODE REVIEW

**Comment by aykevl** [comment]
How does this relate to the mpu6050 driver that's already there? As far as I know, both chips are very similar (with the mpu9250 only adding a sensor).

**Comment by conejoninja** [comment]
They are very similar, not sure what are the exact differences besides the added magnetometer (AK8963). Maybe there should be a common "mpu-xxxx" driver

**Comment by deadprogram** [comment]
I am just wondering if perhaps instead of adding a whole new driver for the MPU9250, instead add a new driver for the AK8963 (in a `package ak8963`). 

Optionally then we can have a `package mpu9250` declare `type Driver mpu6050.Driver` or something like that.

Anyone have thoughts on that?

**Comment by conejoninja** [comment]
That could work, and will make things easier to maintain. I couldn't find a AK8963-only board to test the driver, only single smd-chip or mpu9250. I'm closing this PR, will open the proper ones when done.

**Comment by conejoninja** [comment]
I think you are required to configure the mpu9250 to allow bypass ( https://github.com/conejoninja/tinygo-drivers/blob/mpu9250/mpu9250/mpu9250.go#L90 maybe it's not needed), but once done, you could access the sensor directly. (In some mode/configuration you could access the AK8963 via MPU6050's EXT_SENS_DATA_XX).

**Pull request closed without merging**
