### PR TITLE
Support for AT24C32/64 2-wire serail EEPROM

### PR DESCRIPTION
**Pull request by conejoninja**
commonly used in DS1307/DS3231 modules

### CODE REVIEW

**Comment by deadprogram** [comment]
Shouldn't this driver implement the `ReadWriter` interface?

https://golang.org/pkg/io/#ReadWriter

**Comment by conejoninja** [comment]
I thought (briefly) about that, you need to specify the address you are reading/writing  at. It could implement ReaderAt and WriterAt interfaces (they use int64 as offset), but not sure how to handle the address/offset with ReadWriter. Any ideas?

**Comment by deadprogram** [comment]
This driver is already doing just that https://github.com/tinygo-org/drivers/blob/master/ds1307/ds1307.go

**Comment by conejoninja** [comment]
*do not merge yet*, I need to perform one more test tomorrow

**Comment by conejoninja** [comment]
It's ready to be merged

**Pull request closed without merging**
