### PR TITLE
lsm303agr: fix I2C address auto increment for multi data read

### PR DESCRIPTION
**Pull request by breml**
fixes: #475

### CODE REVIEW

**Comment by breml** [comment]
CC: @ysoldak, @alankrantas

**Comment by breml** [comment]
I confirm, that my test application, which uses the accelerometer works on both, micro:bit v1.5 and V2.2. I didn't test the other two sensors though, because I don't have a meaningful test app available.

**Comment by alankrantas** [comment]
Can confirm that micro:bit v1.5 and v2.0 works (with the official example, which use all three sensors) after applying the patch.

**Comment by breml** [comment]
@deadprogram This PR has been tested successfully on microbit V1.5, V2.0 and V2.2 (see above).
For the reasoning and the details also see #475.

I think, this PR is ready to be merged.

**Comment by deadprogram** [comment]
Thank you very much for the fix @breml and to @alankrantas for testing. Now merging.

**Pull request merged**
