### PR TITLE
drivers: add pca9685 PWM driver

### PR DESCRIPTION
**Pull request by soypat**
Not yet tested. Can't get i2c to work on my pico with this device, it seems to be a problem with 5V vs 3V3 logic level.

If someone can test I'd be very grateful!

### CODE REVIEW

**Comment by soypat** [comment]
Tested it and works great! Please take a look!
@aykevl @sago35 @deadprogram

**Comment by deadprogram** [comment]
@soypat can you please rebase against the latest `dev`? I think that might get the CI passing. Thank you!

**Comment by soypat** [comment]
Enforced Go-Format is failing :shrug:. Curiously, I have not modified any of the files listed.
```
#!/bin/bash -eo pipefail
make fmt-check
Unformatted:
  ./examples/ws2812/arduino.go
  ./examples/ws2812/digispark.go
  ./examples/ws2812/others.go
  ./examples/ws2812/qtpy.go
make: *** [Makefile:8: fmt-check] Error 1

Exited with code exit status 2
CircleCI received exit code 2
```

**Comment by soypat** [comment]
Ah,  a complete rebase is needed. OK. I think I'm better off fetching on dev and rebranching the changes

**Pull request closed without merging**
