### PR TITLE
nit: increase verbosity of espat NetNotify error

### PR DESCRIPTION
**Pull request by leongross**

### CODE REVIEW

**Comment by deadprogram** [comment]
@leongross please run `go fmt` on this change.

Also, please note that I changed the target branch for the PR to `dev` as is typical with the `tinygo-org` repos. Please see https://github.com/tinygo-org/drivers/blob/release/CONTRIBUTING.md#how-to-use-our-github-repository

Thanks!

**Comment by leongross** [comment]
@deadprogram done

**Comment by leongross** [comment]
@deadprogram are you okay with the last patch? then we could merge this real quick

**Comment by deadprogram** [comment]
Thanks for doing this @leongross I will squash/merge to simplify our lives on this change.

**Pull request merged**
