### PR TITLE
(#501) make IP.String() method return something sensible

### PR DESCRIPTION
**Pull request by vjanelle**

### CODE REVIEW

**Comment by deadprogram** [comment]
Hello @vjanelle thanks for pointing out this problem.

It would be better to solve it in a way that avoid using the `fmt` package, because that package makes heavy use of reflection which greatly increases the memory footprint.

Also, please make all PRs against the `dev` branch. Please see https://github.com/tinygo-org/drivers/blob/release/CONTRIBUTING.md#how-to-use-our-github-repository for more info.

Thank you!

**Comment by vjanelle** [comment]
np!  I saw somewhere else this being done with just concat, I'll try that instead.

**Comment by vjanelle** [comment]
@deadprogram reimplemented, added a test to cover the change

**Comment by deadprogram** [comment]
Thank you very much @vjanelle now merging.

**Comment by deadprogram** [comment]
I did not realize it at the time I reviewed this PR, but it has the unintentional side effect of breaking code such as the Drivers `net/mqtt` packages. The mismatch between the IP `wifinina` package and the `net` package result in invalid IP addresses being used during actual usage.

Since the upcoming refactor of `netdev` changes this for the actual correct Go implementation, I think it is better to just revert this PR instead of trying to fix it.

Sorry I did not do a more complete review/testing at the time @vjanelle and hope it does not inconvenience.

**Pull request merged**
