### PR TITLE
modules: switch to use tinygo-org version of tinyfs package

### PR DESCRIPTION
**Pull request by deadprogram**
This PR switches to use the tinygo-org version of the tinyfs package, as discussed in https://github.com/tinygo-org/tinyfs/issues/7#issuecomment-868954816

### CODE REVIEW

**Comment by sago35** [comment]
@deadprogram 
Please run `go mod tidy`.
You can run it by configuring GOROOT, which is displayed by `tinygo info xiao`.
The following is an example of command execution.
It is probably a good idea to update it.


```
$ GOROOT=/c/Users/sago3/AppData/Local/tinygo/goroot-go1.16-641d833c9cde99e59ff7f49213b86411a51f7b285c3bdc52fcd17d2b43471339-syscall go mod tidy

```

**Comment by deadprogram** [comment]
I did already run `go mod tidy` on this branch before creating the PR.

**Comment by sago35** [comment]
Oops.
I had the following file in my environment, which changed the result of go mod tidy.
I deleted them and the difference disappeared.

```
$ find . -name generic.go
./examples/rtl8720dn/tlsclient/generic.go
./examples/rtl8720dn/webclient/generic.go
./examples/rtl8720dn/webclient-tinyterm/generic.go
```

All the code is correct.

**Review by sago35 — APPROVED** [review]

**Comment by deadprogram** [comment]
Thanks @sago35 for review. Now merging.

**Pull request merged**
