### PR TITLE
ssd1306 Add getter method on display buffer

### PR DESCRIPTION
**Pull request by alexjomin**
Hi there, 

I think I could be great to have a getter method to retrieve the buffer, so we could iterate over the slice to apply an effect on the whole screen for example. 

Feel free to comment and thank you for the awesome work on TinyGo!

### CODE REVIEW

**Review by deadprogram — APPROVED** [review]
Seems reasonable to me. Can we also add this to the other displays?

@conejoninja @sago35 ?

**Comment by conejoninja** [comment]
Yes, this could be added to other displays with buffer (not all have because of size), I think some of them (mostly monochrome) already have a getter, but I'll check them.

**Comment by alexjomin** [comment]
Thank you for the review, let me know if I can help.

**Comment by deadprogram** [comment]
Thanks @alexjomin now merging.

**Pull request merged**
