### PR TITLE
ws2812: add support for qtpy and atsame5x

### PR DESCRIPTION
**Pull request by sago35**
This PR allows qtpy and atsame5x to run examples/ws2812 without any changes.

### CODE REVIEW

**Comment by sago35** [comment]
I see that examples/ws2812 depends on machine.LED.

```
$ tinygo flash --target qtpy --size short ./examples/ws2812/
# tinygo.org/x/drivers/examples/ws2812
examples\ws2812\main.go:18:17: LED not declared by package machine
```

**Comment by sago35** [comment]
Checked build and flash with feather-m4-can and qtpy.

```
$ tinygo build -o /tmp/a.uf2 --target qtpy --size short --programmer cmsis-dap ./examples/ws2812/
   code    data     bss |   flash     ram
   7728      36    4332 |    7764    4368

$ tinygo build -o /tmp/a.uf2 --target feather-m4-can --size short --programmer cmsis-dap ./examples/ws2812/
   code    data     bss |   flash     ram
   8108      36    6380 |    8144    6416
```

**Comment by sago35** [comment]
Now ready for review.

**Review by aykevl — APPROVED** [review]
Looks good to me. I don't think we need an example for every supported board, but it's okay to add one.

**Comment by deadprogram** [comment]
Thanks @sago35 for the PR and @aykevl for reviewing. Now merging.

**Pull request merged**
